### ISSUE TITLE
pytopol folder missing

### ISSUE THREAD

**Issue by revthi** [resal81/PyTopol#24]
Dear Sir,
I tried downloading versions 0.10,  0.1.1  and 0.1.6 of pytopol. none of them seems to contain the folder parsers.
I did:
tar -xvzf pytopol-0.1.6.tar.gz 
cd pytopol          ( no parsers folder)
export PYTHONPATH=`pwd`:$PYTHONPATH
cd scripts
python2.7 psf2top.py

and the error is:

Traceback (most recent call last):
  File "./psf2top.py", line 29, in <module>
    from pytopol.parsers import charmmpar, grotop, psf
ImportError: No module named pytopol.parsers

Kindly help me resolve this issue

Thank you.
Revathi

**Comment by zonca** [comment]
@resal81 I confirm the pip package is broken.

the package from:
https://pypi.python.org/pypi/pytopol/

does not contain the subpackages parsers and general, I'll submit a PR to fix this.

**Comment by resal81** [comment]
@zonca Thanks!

**Comment by resal81** [comment]
So version 0.1.7 should be on PyPI. 

By the way, I'm also experimenting with a similar toolkit in Go (https://github.com/resal81/molkit). It's really alpha but if you're interested, take a look at it too!
