### ISSUE TITLE
gromacs parser

### ISSUE THREAD

**Issue by sanasaeed** [resal81/PyTopol#27]
can you guide me about this error, how should i fix it.

Traceback (most recent call last):
  File "alchemical_analysis.py", line 1076, in <module>
    import parsers.parser_gromacs
ImportError: No module named parsers.parser_gromacs

**Comment by resal81** [comment]
I'm not sure that this is related to PyTopol (there's no file `parser_gromacs` to be imported in PyTopol). Maybe you're using [alchemical-analysis](https://github.com/MobleyLab/alchemical-analysis) and not PyTopol?

**Comment by sanasaeed** [comment]
oh sorry i submit it to wrong place.

**Comment by resal81** [comment]
No problem!
